2024-12-28 19:50:42,901 INFO    MainThread:106189 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/.config/wandb/settings
2024-12-28 19:50:42,901 INFO    MainThread:106189 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-50-41/wandb/settings
2024-12-28 19:50:42,901 INFO    MainThread:106189 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2024-12-28 19:50:42,902 WARNING MainThread:106189 [wandb_setup.py:_flush():75] Could not find program at -m classification.training.trainer
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m classification.training.trainer'}
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_init.py:_log_setup():437] Logging user logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-50-41/wandb/run-20241228_195042-3710qqfm/logs/debug.log
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_init.py:_log_setup():438] Logging internal logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-50-41/wandb/run-20241228_195042-3710qqfm/logs/debug-internal.log
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_init.py:init():471] calling init triggers
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {}
2024-12-28 19:50:42,902 INFO    MainThread:106189 [wandb_init.py:init():524] starting backend
2024-12-28 19:50:42,905 INFO    MainThread:106189 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 19:50:42,907 INFO    MainThread:106189 [wandb_init.py:init():533] backend started and connected
2024-12-28 19:50:42,911 INFO    MainThread:106189 [wandb_init.py:init():597] updated telemetry
2024-12-28 19:50:42,931 INFO    MainThread:106189 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2024-12-28 19:50:45,962 WARNING MsgRouterThr:106189 [router.py:message_loop():76] message_loop has been closed
