2024-12-28 19:45:14,174 INFO    MainThread:92146 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/.config/wandb/settings
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_setup.py:_flush():75] Loading settings from /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-42-54/wandb/settings
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'_require_service': 'True'}
2024-12-28 19:45:14,175 WARNING MainThread:92146 [wandb_setup.py:_flush():75] Could not find program at -m classification.training.trainer
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m classification.training.trainer'}
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_init.py:_log_setup():437] Logging user logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-42-54/wandb/run-20241228_194514-zedj7m5b/logs/debug.log
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_init.py:_log_setup():438] Logging internal logs to /home/awc2159/projects/MeTra_3D/outputs/2024-12-28/19-42-54/wandb/run-20241228_194514-zedj7m5b/logs/debug-internal.log
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_init.py:init():471] calling init triggers
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_init.py:init():474] wandb.init called with sweep_config: {}
config: {}
2024-12-28 19:45:14,175 INFO    MainThread:92146 [wandb_init.py:init():524] starting backend
2024-12-28 19:45:14,180 INFO    MainThread:92146 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-28 19:45:14,184 INFO    MainThread:92146 [wandb_init.py:init():533] backend started and connected
2024-12-28 19:45:14,188 INFO    MainThread:92146 [wandb_init.py:init():597] updated telemetry
2024-12-28 19:45:14,214 INFO    MainThread:92146 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2024-12-28 19:45:17,243 WARNING MsgRouterThr:92146 [router.py:message_loop():76] message_loop has been closed
2024-12-28 19:45:42,335 WARNING MainThread:92146 [wandb_init.py:init():1016] interrupted
Traceback (most recent call last):
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 629, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 324, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/awc2159/.conda/envs/metra/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
